// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedditMockup.DataAccess.Context;

#nullable disable

namespace RedditMockup.DataAccess.Migrations
{
    [DbContext(typeof(RedditMockupContext))]
    [Migration("20221008084632_5")]
    partial class _5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RedditMockup.Model.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(7351),
                            Description = "uliteieopuaiunusaqudenasaaeqev",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(7351),
                            QuestionId = 1,
                            Title = "erseaptr",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8157),
                            Description = "mrououstetndgteadiiqaamieevipu",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8157),
                            QuestionId = 1,
                            Title = "esetuluv",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8506),
                            Description = "leaettiedorsouoensbmacrirtsuit",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8506),
                            QuestionId = 1,
                            Title = "umttuqui",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8823),
                            Description = "ldermtruaaneruasrtueiemufueomr",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(8823),
                            QuestionId = 1,
                            Title = "uuiendda",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9188),
                            Description = "eotssstuaaeieuqinusuapsttsttoa",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9188),
                            QuestionId = 1,
                            Title = "tuileouu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9513),
                            Description = "qtcmusnlasieaaetbisodeqmtmohdh",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9513),
                            QuestionId = 1,
                            Title = "unimteis",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9825),
                            Description = "huuiettoiumameiseutnaiuviieatt",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 134, DateTimeKind.Local).AddTicks(9825),
                            QuestionId = 1,
                            Title = "uerqtqhe",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(132),
                            Description = "tsaehiiuuauuurninqeeiiepeenqes",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(132),
                            QuestionId = 1,
                            Title = "nseeqlic",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(479),
                            Description = "lctairquutmssaiorhiaeunseaiiuc",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(479),
                            QuestionId = 1,
                            Title = "dupoepmd",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(802),
                            Description = "mrseenodlttueegeiurlxqstmosoup",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 135, DateTimeKind.Local).AddTicks(802),
                            QuestionId = 1,
                            Title = "qoqoqrea",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.AnswerVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Kind")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("AnswerVotes");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(498),
                            Family = "Foroughi Rad",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(498),
                            Name = "Sepehr"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(503),
                            Family = "BooAzaar",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(503),
                            Name = "Abbas"
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "",
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1043),
                            Email = "",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1043),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Bio = "",
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1058),
                            Email = "",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1058),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(1908),
                            Description = "ulialolstruemuinrtusimiliiudou",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(1908),
                            Title = "sttiiiad",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(2804),
                            Description = "ulunsiieqaudnsruetqeuauuqsiiqo",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(2804),
                            Title = "uruamuio",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3191),
                            Description = "aoilmuocsvuuaqruistuutniustsum",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3191),
                            Title = "optelose",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3537),
                            Description = "nsuutnitclunotdscuitruurmusdpd",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3537),
                            Title = "rlcdieiu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3869),
                            Description = "uoasseuaruoiigueiiueetetvuouim",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(3869),
                            Title = "adiudauc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4206),
                            Description = "oroitlieltsimhimisnalatmicxomi",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4206),
                            Title = "mraiutde",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4520),
                            Description = "rnonlxsenetnounissroiisitrouei",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4520),
                            Title = "oaoptxuc",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4836),
                            Description = "uitiatooulnquapafaelsuuciouqat",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(4836),
                            Title = "vtiirioa",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(5155),
                            Description = "eeuueitxnecetsiosbaagcrovssmqp",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(5155),
                            Title = "etuiraqn",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(5564),
                            Description = "vnuaioagearooathaomoeuurutsilu",
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 132, DateTimeKind.Local).AddTicks(5564),
                            Title = "iimtoeas",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.QuestionVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Kind")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionVotes");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(428),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(428),
                            Title = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(469),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(469),
                            Title = "User"
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(524),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(524),
                            Password = "7f13d2c6d8191aaec19c5bb484deb750d7c79ce6d546815acbde63cbd857053310492804a674a16bfb18550e3e16df3c4bbd9801288e735057eb5010caa37ab8",
                            PersonId = 1,
                            Score = 0,
                            Username = "sepehr_frd"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(911),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(911),
                            Password = "7cabe918dbd1e1ddbf57e0c17c636f6ce8153bbbd7c460edc774b09dfde1e42fa63501e088c6df3bb630fba5e92781aa0997aca1d2a4aee63c93348bf61f2576",
                            PersonId = 2,
                            Score = 0,
                            Username = "abbas_booazaar"
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1079),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1079),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1083),
                            LastUpdated = new DateTime(2022, 10, 8, 12, 16, 32, 129, DateTimeKind.Local).AddTicks(1083),
                            RoleId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Answer", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedditMockup.Model.Entities.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.AnswerVote", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.Answer", "Answer")
                        .WithMany("Votes")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Profile", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("RedditMockup.Model.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Question", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.QuestionVote", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.Question", "Question")
                        .WithMany("Votes")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.User", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("RedditMockup.Model.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.UserRole", b =>
                {
                    b.HasOne("RedditMockup.Model.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedditMockup.Model.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Answer", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RedditMockup.Model.Entities.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Profile");

                    b.Navigation("Questions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
