services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}"
      - "Trust_Server_Certificate=True"
    ports:
      - "1533:1433"
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'SELECT 1'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1524M'

  insight-flow:
    image: local/insight-flow:2.0.0
    build:
      context: .
      dockerfile: ./src/InsightFlow.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SqlServerConnectionString: "Server=sqlserver,1433;Database=InsightFlow;User Id=sa;Password=${MSSQL_SA_PASSWORD};Trust Server Certificate=True;Encrypt=False;Connect Timeout=120"
      ApplicationInformation__Name: "InsightFlow"
      ApplicationInformation__Version: "2.0.0"
      ApplicationInformation__ServerUrl: "http://localhost"
      ApplicationInformation__ClientUrl: "http://localhost"
      ContactInformation__Name: "Sepehr Foroughi Rad"
      ContactInformation__Url: "https://github.com/sepehr-frd"
      ContactInformation__Email: "sepfrd@outlook.com"
      JwtOptions__PrivateKey: "-----BEGIN PRIVATE KEY-----\n{Your Private Key Here}\n-----END PRIVATE KEY-----"
      JwtOptions__PublicKey: "-----BEGIN PUBLIC KEY-----\n{Your Public Key Here}\n-----END PUBLIC KEY-----"
      JwtOptions__TokenExpirationDurationMinutes: 1440
      PaginationOptions__MinimumAllowedPageSize: 1
      PaginationOptions__MaximumAllowedPageSize: 100
      ProfileImageMaximumAllowedBytes: 2097152
      RateLimitersConfiguration__FixedWindowRateLimiterOptions__PermitLimit: 5
      RateLimitersConfiguration__FixedWindowRateLimiterOptions__WindowSeconds: 120
      RateLimitersConfiguration__FixedWindowRateLimiterOptions__QueueLimit: 0
      RateLimitersConfiguration__FixedWindowRateLimiterOptions__QueueProcessingOrder: 0
      RateLimitersConfiguration__FixedWindowRateLimiterOptions__AutoReplenishment: true
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__ReplenishmentPeriodSeconds: 10
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__TokensPerPeriod: 10
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__AutoReplenishment: true
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__TokenLimit: 100
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__QueueProcessingOrder: 0
      RateLimitersConfiguration__TokenBucketRateLimiterOptions__QueueLimit: 0
      RateLimitersConfiguration__ConcurrencyLimiterOptions__PermitLimit: 100
      RateLimitersConfiguration__ConcurrencyLimiterOptions__QueueProcessingOrder: 0
      RateLimitersConfiguration__ConcurrencyLimiterOptions__QueueLimit: 0
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: on-failure