@InsightFlow.Api_HostAddress = http://localhost:7000

GET {{InsightFlow.Api_HostAddress}}/ping/
Accept: application/json

###

GET {{InsightFlow.Api_HostAddress}}/blogposts
Accept: application/json

###

POST {{InsightFlow.Api_HostAddress}}/blogposts
Content-Type: application/json
Accept: application/json

{
    "Title": "Some title about testing this endpoint",
    "Body": "Some title about testing this endpoint Some title about testing this endpoint Some title about testing this endpoint",
    "AuthorId": "4F4F3AA4-C3F1-4445-9E66-CCD8858AACEB"
}

