//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Common.Resources.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        public static string PropertyNotUnique {
            get {
                return ResourceManager.GetString("PropertyNotUnique", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        public static string IdenticalNewPropertyValues {
            get {
                return ResourceManager.GetString("IdenticalNewPropertyValues", resourceCulture);
            }
        }
        
        public static string IdenticalNewValue {
            get {
                return ResourceManager.GetString("IdenticalNewValue", resourceCulture);
            }
        }
        
        public static string ForbiddenAction {
            get {
                return ResourceManager.GetString("ForbiddenAction", resourceCulture);
            }
        }
        
        public static string EntityNotFoundByUuid {
            get {
                return ResourceManager.GetString("EntityNotFoundByUuid", resourceCulture);
            }
        }
        
        public static string EntityNotFoundById {
            get {
                return ResourceManager.GetString("EntityNotFoundById", resourceCulture);
            }
        }
        
        public static string SuccessfulLogin {
            get {
                return ResourceManager.GetString("SuccessfulLogin", resourceCulture);
            }
        }
        
        public static string SuccessfulUpdate {
            get {
                return ResourceManager.GetString("SuccessfulUpdate", resourceCulture);
            }
        }
        
        public static string SuccessfulDelete {
            get {
                return ResourceManager.GetString("SuccessfulDelete", resourceCulture);
            }
        }
        
        public static string ApplicationFatalException {
            get {
                return ResourceManager.GetString("ApplicationFatalException", resourceCulture);
            }
        }
        
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
    }
}
